sudo: false
dist: bionic
cache:
  directories:
    - "$HOME/.m2"
language: java
before_install:
  - sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g' ~/.m2/settings.xml
  - unset _JAVA_OPTIONS
  - if [[ "$TRAVIS_JOB_NAME" == MySQL* ]]; then
       sh ".travis/start-mysql.sh" $MYSQL;
       sh ".travis/setup-mysql.sh";
    fi

install: 
env:
  global:
    - MAVEN_OPTS=-Xmx756m
script:
  - mvn -B -fae -Dall clean install -T2 $ARGS
notifications:
  email: false
  on_failure: never
addons:
  apt:
    packages:
      - python-sphinx
matrix:
  include:
    - jdk: openjdk8
      env: ARGS="-Dfmt.skip=true"
    - jdk: openjdk11
      env: ARGS="-Dfmt.skip=true -Pjdk11tests"
    - jdk: openjdk11
      env: ARGS="-Dfmt.action=check -Dqa=true -DskipTests=true"
    - jdk: openjdk8
      env: ARGS="-pl :gt-jdbc-mysql -Ponline -Dfmt.skip=true -am" MYSQL="5"
      dist: bionic
      name: "MySQL 5"
      services:
        - docker
      addons:
        apt:
          packages:
            - docker-ce
    - jdk: openjdk11
      env: ARGS="-pl :gt-jdbc-mysql -Ponline -Dfmt.skip=true -am" MYSQL="8"
      dist: bionic
      name: "MySQL 8"
      services:
        - docker
      addons:
        apt:
          packages:
            - docker-ce
